name: tispillo_official
description: "Powered by Nearcons"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_form_builder: ^9.7.0
  form_builder_validators: ^11.1.1
  salomon_bottom_bar: ^3.3.2
  supabase_flutter: ^2.8.3
  flutter_dotenv: ^5.2.1
  intl: ^0.19.0
  timezone: ^0.10.0
  uuid: ^4.5.1
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/flags/
    - assets/logo/
    - assets/l10n/
